module.exports = [
  {
    slug: "little-miss-sunshine",
    title: "Little Miss Sunshine",
    mood: "Feeling Lost",
    genre: "Comedy-Drama",
    year: 2006,
    streaming: "Hulu",
    image: "/images/littleMissSunShine.jpg",
    shortDescription: "A chaotic family road trip that somehow heals everyone.",
    fullDescription:
      "A dysfunctional family travels across the country so their young daughter can compete in a beauty pageant...",
  },
  {
    slug: "the-intern",
    title: "The Intern",
    mood: "Need Comfort",
    genre: "Comedy",
    year: 2015,
    streaming: "Max",
    image: "/images/the_intern.jpg",
    shortDescription: "A heartwarming story about mentorship and friendship.",
    fullDescription:
      "A 70-year-old widower becomes an intern at an online fashion company...",
  },
  {
    slug: "perks-of-being-a-wallflower",
    title: "The Perks of Being a Wallflower",
    mood: "Feeling Emotional",
    genre: "Drama",
    year: 2012,
    streaming: "Netflix",
    image: "/images/perks.jpg",
    shortDescription: "A coming-of-age story about friendship and healing.",
    fullDescription:
      "An introverted high school freshman is taken under the wings of two seniors...",
  },
  {
    slug: "crazy-rich-asians",
    title: "Crazy Rich Asians",
    mood: "Romantic Mood",
    genre: "Romance",
    year: 2018,
    streaming: "Prime Video",
    image: "/images/crazy-rich-asians.jpg",
    shortDescription: "Lavish romance meets family drama.",
    fullDescription:
      "A New Yorker accompanies her boyfriend to Singapore and discovers his family is insanely wealthy...",
  },
  {
    slug: "secret-life-of-walter-mitty",
    title: "The Secret Life of Walter Mitty",
    mood: "Adventure Craving",
    genre: "Adventure",
    year: 2013,
    streaming: "Disney+",
    image: "/images/walter-mitty.jpg",
    shortDescription: "A daydreamer escapes into real-life adventure.",
    fullDescription: "A timid magazine employee embarks on a global journey...",
  },
];
